Fix IllegalArgumentException with AGP > 7.1.3
Using GmsCore with AGP > 7.1.3 causes:

```
java.lang.Exception: java.lang.IllegalArgumentException
..at com.google.android.gms.dynamic.ObjectWrapper.unwrap(ObjectWrapper.java:43)
```